// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.Examplekind":       schema_pkg_apis_example_v1alpha1_Examplekind(ref),
		"github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.ExamplekindSpec":   schema_pkg_apis_example_v1alpha1_ExamplekindSpec(ref),
		"github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.ExamplekindStatus": schema_pkg_apis_example_v1alpha1_ExamplekindStatus(ref),
	}
}

func schema_pkg_apis_example_v1alpha1_Examplekind(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Examplekind is the Schema for the examplekinds API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.ExamplekindSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.ExamplekindStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.ExamplekindSpec", "github.com/speak2jc/j-op/pkg/apis/example/v1alpha1.ExamplekindStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_example_v1alpha1_ExamplekindSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ExamplekindSpec defines the desired state of Examplekind",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_example_v1alpha1_ExamplekindStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ExamplekindStatus defines the observed state of Examplekind",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
