apiVersion: apps/v1
kind: Deployment
metadata:
  name: j-op
spec:
  replicas: 1
  selector:
    matchLabels:
      name: j-op
  template:
    metadata:
      labels:
        name: j-op
    spec:
      serviceAccountName: j-op
      containers:
        - name: j-op
          # Replace this with the built image name
          image: speak2jc/j-op:v0.0.1
          command:
          - j-op
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "j-op"
